(defpackage :bianet-neuron
  (:use :cl :dc-dlist :dc-eclectic :sb-concurrency :sb-thread :cl-ppcre)
  (:export
   activation-count
   adjust-weight
   apply-inputs
   apply-error
   biased
   bp-count
   close-log
   connect
   dlog
   t-cx
   delta
   disable
   disconnect
   enable
   enabled
   err
   err-input
   excitation-count
   excite
   feed-forward
   ff-count
   id
   incoming
   input
   isolate
   last-err
   last-err-input
   last-input
   last-output
   last-weight
   layer
   learning-rate
   list-incoming
   list-incoming-weights
   list-neuron-threads
   list-outgoing
   list-outputs
   modulate
   modulated
   modulation-count
   momentum
   name
   weight-history
   open-log
   outgoing
   output
   output-layer-error
   received
   source
   t-neuron
   target
   train-frame
   transfer
   transfer-count
   transfer-error
   transfer-function
   transfer-derivative
   update-count
   wait-for-backprop
   wait-for-backprop-p
   wait-for-output
   wait-for-output-p
   weight
   with-neurons
   ))
