(defpackage :bianet-neuron
  (:use :cl :dc-dlist :dc-eclectic :sb-concurrency :sb-thread :cl-ppcre)
  (:export
   activation-count
   biased
   bp-count
   connect
   delta
   disable
   disconnect
   enable
   enabled
   err
   err-input
   excitation-count
   excite
   ff-count
   id
   incoming
   input
   isolate
   learning-rate
   list-incoming
   list-incoming-weights
   list-neuron-threads
   list-outputs
   modulated
   modulation-count
   momentum
   name
   outgoing
   output
   received
   source
   t-neuron
   target
   transfer-count
   transfer-function
   transfer-derivative
   update-count
   weight
   weight-history
   ))
